sudo pacman -Syu \
    alacritty \
    amd-ucode \
    base \
    base-devel \
    basedpyright-bin \
    bash-language-server \
    bluetui \
    bluez \
    bluez-utils \
    brightnessctl \
    btop \
    c-ares \
    ccache \
    clang \
    cmake \
    cups \
    cups-pk-helper \
    delve \
    dkms \
    docker \
    docker-compose \
    doxygen \
    efibootmgr \
    eslint \
    eslint-language-server \
    eza \
    fastfetch \
    firefox \
    flamegraph \
    fuse2 \
    fzf \
    gcc \
    gdb \
    git \
    git-lfs \
    gitui \
    go \
    gopls \
    gradle \
    grpc \
    gst-plugin-pipewire \
    hiredis \
    htop \
    jdtls \
    jsoncpp \
    kotlin \
    kotlin-lsp-bin \
    krita \
    kubectl \
    lemurs \
    less \
    libpulse \
    libreoffice-fresh \
    libva-nvidia-driver \
    libwebsockets \
    linux \
    linux-firmware \
    linux-headers \
    lld \
    llvm \
    lsof \
    lua-language-server \
    luajit \
    make \
    mako \
    mariadb-libs \
    markdown-oxide \
    maven \
    ncdu \
    networkmanager \
    ninja \
    niri \
    nlohmann-json \
    nvidia-open-dkms \
    obs-cmd \
    obs-studio \
    openssh \
    pipewire \
    pipewire-alsa \
    pipewire-jack \
    pipewire-libcamera \
    pipewire-pulse \
    pipewire-session-manager \
    pipewire-v4l2 \
    pkgfile \
    playerctl \
    podman \
    podman-compose \
    postgresql-libs \
    power-profiles-daemon \
    prettier \
    python-pip \
    python-virtualenv \
    rapidjson \
    rbenv \
    ripgrep \
    rofi \
    ruby-build \
    ruff \
    rust-analyzer \
    rustup \
    sdl3_image \
    sdl3_ttf \
    sdl_gfx \
    sdl_image \
    sdl_net \
    sdl_sound \
    sdl_ttf \
    simdjson \
    sof-firmware \
    speech-dispatcher \
    sqls \ 
    squiid \
    strace \
    sudo \ 
    superfile \
    svelte-language-server \
    swaybg \
    swayimg \
    system-config-printer \
    systemd-language-server \
    tailwindcss-language-server \
    taskwarrior-tui \
    telegram-desktop \
    tree-sitter-cli \
    ttf-cascadia-code \
    ttf-cascadia-code-nerd \
    ttf-cascadia-mono-nerd \
    ttf-fira-code \
    ttf-fira-mono \
    ttf-fira-sans \
    ttf-firacode-nerd \
    ttf-jetbrains-mono \
    ttf-jetbrains-mono-nerd \
    ttf-material-icons \
    ttf-montserrat \
    ttf-roboto \
    ttf-roboto-mono \
    ttf-roboto-mono-nerd \
    typescript-language-server \
    unzip \
    uv \
    valgrind \
    vim \
    vim-spell-en \
    vscode-css-languageserver \
    vscode-html-languageserver \
    vscode-json-languageserver \
    vue-language-server \
    vulkan-validation-layers \
    waybar \
    wayland-docs \
    wayland-protocols \
    wayland-utils \
    waylandpp \
    wget \
    wireplumber \
    wl-clipboard \
    wrk \
    wscat \
    xdg-desktop-portal \
    xdg-desktop-portal-wlr \
    xdg-desktop-portal-gnome \
    yaml-cpp \
    yaml-language-server \
    yarn \
    yay \
    yay-debug \
    zed \
    zip \
    zram-generator ;
