set updatetime=60
set timeoutlen=600

" set mouse=nvi

syntax on
set number

set tabstop=4
set expandtab
set shiftwidth=4
set smartindent
set softtabstop=4

set clipboard=unnamedplus

set laststatus=3

" load here
"source ~/.vim/theme.vim
